# Generated by Django 5.2 on 2025-04-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('common_use', models.TextField()),
                ('preparation', models.TextField()),
                ('precautions', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='herb_images/')),
            ],
        ),
    ]
