# Generated by Django 5.2 on 2025-04-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='image',
        ),
    ]
