# Generated by Django 5.2 on 2025-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0002_remove_herb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='herb_images/'),
        ),
    ]
