# Generated by Django 5.2 on 2025-05-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0003_herb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='location',
            field=models.CharField(default='Unknown', help_text='Where this herb is commonly found', max_length=255),
            preserve_default=False,
        ),
    ]
